# site properties and page defaults
title: Ajou Health Data Science Lab
subtitle: 
description: Ajou Health Data Science Lab leds by Dr. Chungsoo Kim
header: images/background2.png
footer: images/background2.png
proofer: false

# site social media and other links
links:
  email: ted9219@gmail.com
  orcid: 0000-0003-1802-1777
  google-scholar: https://scholar.google.com/citations?user=9smDt4kAAAAJ&hl=en
  github: ChungsooKim
  twitter: Chungsoo_
  linkedin: chungsoo-kim-42419b175/

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
